CREATE DATABASE EMPRESA_KAUE;
GO

USE EMPRESA_KAUE;
GO

CREATE TABLE PESSOA(
 idPessoa SMALLINT PRIMARY KEY IDENTITY(1,1),
 nomePessoa VARCHAR(20) NOT NULL
);
GO

INSERT INTO PESSOA (nomePessoa)
VALUES ('SAULO'), ('LUCAS');
GO

SELECT * FROM PESSOA

CREATE TABLE TELEFONE(
 idTelefone SMALLINT PRIMARY KEY IDENTITY(1,1),
 idPessoa SMALLINT FOREIGN KEY REFERENCES PESSOA(idPessoa),
 numeroTelefone VARCHAR(15) NOT NULL
);
GO

INSERT INTO TELEFONE (idPessoa, numeroTelefone)
VALUES (3, '999'), (3, '888'), (4,'777');
GO

SELECT * FROM TELEFONE

CREATE TABLE EMAIL(
 idEmail INT PRIMARY KEY IDENTITY(1,1),
 idPessoa SMALLINT FOREIGN KEY REFERENCES PESSOA(idPessoa),
 end_email VARCHAR(256) NOT NULL
);
GO

INSERT INTO EMAIL (idPessoa, end_email)
VALUES (3, 'saulo@email.com') , (4, 'lucas@email.com');
GO

SELECT * FROM EMAIL

CREATE TABLE CNH(
 idCNH SMALLINT PRIMARY KEY IDENTITY(1,1),
 idPessoa SMALLINT FOREIGN KEY REFERENCES PESSOA(idPessoa),
 descricao CHAR(11) NOT NULL UNIQUE
);
GO

INSERT INTO CNH (idPessoa, descricao)
VALUES (3, '132')

INSERT INTO CNH (idPessoa, descricao)
VALUES (4, '4343')

SELECT * FROM CNH

SELECT * FROM CNH
SELECT * FROM EMAIL
SELECT * FROM TELEFONE
SELECT * FROM PESSOA