CREATE DATABASE LOCADORA_KAUE;
GO

USE LOCADORA_KAUE;
GO

CREATE TABLE EMPRESA(
 idEmpresa SMALLINT PRIMARY KEY IDENTITY(1,1),
 nomeEmpresa VARCHAR(30) NOT NULL
);
GO

INSERT INTO EMPRESA(nomeEmpresa)
VALUES ('SPACE'), ('SENAI');
GO

SELECT * FROM EMPRESA

CREATE TABLE MARCA(
 idMarca SMALLINT PRIMARY KEY IDENTITY(1,1),
 nomeMarca VARCHAR(20) NOT NULL
);
GO

INSERT INTO MARCA(nomeMarca)
VALUES ('FORD'), ('TESLA');
GO

UPDATE MARCA SET nomeMarca = 'HYUNDAI'
WHERE idMarca = 1

SELECT * FROM MARCA

CREATE TABLE MODELO(
 idModelo SMALLINT PRIMARY KEY IDENTITY(1,1),
 idMarca SMALLINT FOREIGN KEY REFERENCES MARCA(idMarca),
 nomeModelo VARCHAR(25) NOT NULL
);
GO

INSERT INTO MODELO(idMarca, nomeModelo)
VALUES (1, 'HB20'), (2, 'CYBERTRUCK');
GO

SELECT * FROM MODELO

CREATE TABLE VEICULO(
 idVeiculo SMALLINT PRIMARY KEY IDENTITY(1,1),
 idModelo SMALLINT FOREIGN KEY REFERENCES MODELO(idModelo),
 idEmpresa SMALLINT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
 placa VARCHAR(10) NOT NULL
);
GO

INSERT INTO VEICULO(idModelo, idEmpresa, placa)
VALUES (2, 2, '3333');
GO

INSERT INTO VEICULO(idModelo, idEmpresa, placa)
VALUES (1, 1, '4444');
GO

SELECT * FROM VEICULO

CREATE TABLE CLIENTE(
 idCLiente SMALLINT PRIMARY KEY IDENTITY(1,1),
 nomeCliente VARCHAR(25) NOT NULL,
 cpfCliente VARCHAR(13) NOT NULL
);
GO

INSERT INTO CLIENTE(nomeCliente, cpfCliente)
VALUES ('LUCAS', '111111'), ('SAULO', '222222');
GO

SELECT * FROM CLIENTE

CREATE TABLE ALUGUEL(
 idAluguel SMALLINT PRIMARY KEY IDENTITY(1,1),
 idVeiculo SMALLINT FOREIGN KEY REFERENCES VEICULO(idVeiculo),
 idCliente SMALLINT FOREIGN KEY REFERENCES CLIENTE(idCliente)
);
GO

INSERT INTO ALUGUEL(idVeiculo, idCliente)
VALUES(1, 2), (2,1);
GO

SELECT * FROM ALUGUEL